version: "3.8"
services:
  # inference server
  app:
    build: 
      context: ../ # Dockerfileを実行する際のディレクトリをrootに設定
      dockerfile: infra/inference_server/Dockerfile
    container_name: inference-server
    ports: 
      - "8000:8000"
    volumes:
      - ../app:/app/app
      - ../model:/app/model
      - ../data:/app/data
      - ../log:/app/log
  # jupyter
  jupyter: 
    build: 
      context: ../
      dockerfile: infra/jupyter/Dockerfile
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ../notebook:/home/jovyan/work
      - ../data:/home/jovyan/data
      - ../model:/home/jovyan/model
      - ../log:/home/jovyan/log
      - ../training:/home/jovyan/training
    command: /bin/bash -c "python /home/jovyan/training/download/download.py && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password='' --allow-root"
